[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
